"""
AI Documentation Generator Service.
"""

from pathlib import Path

from src.core.logger import logger
from src.services.architecture_service import ArchitectureService
from src.services.code_graph_service import CodeGraphService


class DocumentationService:

    def __init__(self):

        self.architecture_service = ArchitectureService()
        self.code_graph_service = CodeGraphService()

        logger.info("DocumentationService initialized")

    def generate(self, repository_path: str):

        root = Path(repository_path).resolve()

        docs_path = root / "docs"

        docs_path.mkdir(exist_ok=True)

        architecture = self.architecture_service.analyze_structure(str(root))

        graph = self.code_graph_service.generate_graph(str(root))

        mermaid = self.code_graph_service.generate_mermaid(graph)

        self.create_architecture_doc(docs_path, architecture, mermaid)

        self.create_modules_doc(docs_path, graph)

        return {
            "documentation_path": str(docs_path),
            "files_created": ["ARCHITECTURE.md", "MODULES.md"],
        }

    def create_architecture_doc(self, docs_path, architecture, mermaid):

        content = (
            "# RepoMind AI Architecture\n\n"
            "## Repository Structure\n\n" + str(architecture) + "\n\n"
            "## Dependency Graph\n\n"
            "```mermaid\n" + mermaid + "\n```\n\n"
            "Generated by RepoMind AI\n"
        )

        (docs_path / "ARCHITECTURE.md").write_text(content, encoding="utf-8")

    def create_modules_doc(self, docs_path, graph):

        lines = []

        lines.append("# RepoMind AI Modules\n")

        for module, dependencies in graph.items():

            lines.append("## " + module + "\n")

            if dependencies:

                lines.append("Dependencies:")

                for dep in dependencies:

                    lines.append("- " + dep)

            else:

                lines.append("No internal dependencies")

            lines.append("")

        (docs_path / "MODULES.md").write_text("\n".join(lines), encoding="utf-8")
