"""
Repository report generation service.
"""

from pathlib import Path

from src.core.logger import logger
from src.services.architecture_service import ArchitectureService
from src.services.code_graph_service import CodeGraphService


class ReportService:

    def __init__(self):

        self.architecture_service = ArchitectureService()
        self.graph_service = CodeGraphService()

        logger.info("ReportService initialized")

    def generate_report(
        self,
        repository_path: str,
    ):

        root = Path(repository_path)

        architecture = self.architecture_service.analyze_structure(repository_path)

        summary = self.architecture_service.generate_architecture_summary(architecture)

        graph = self.graph_service.generate_graph(repository_path)

        report = f"""
==============================
 RepoMind AI Repository Report
==============================

Repository:
{root.name}


Architecture:
{summary}


Components:
"""

        for component in architecture.get("components", []):

            report += f"- {component['name']}\n"

        report += """

Dependency Overview:
"""

        for module, dependencies in graph.items():

            if dependencies:

                report += f"\n{module} depends on:"

                for dependency in dependencies:

                    report += f"\n  - {dependency}"

        report += """

==============================
 Generated by RepoMind AI
==============================
"""

        return report
